[advisories]
ignore = [
    "RUSTSEC-2020-0056",
    "RUSTSEC-2020-0071",
    "RUSTSEC-2020-0159"
]

[licenses]
allow = [
    "MPL-2.0",
    "OpenSSL"
]
allow-osi-fsf-free = "both"
exceptions = [
    { allow = ["AGPL-3.0"], name = "aoc_bot", version = "*" },
]

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]

[bans]
skip = [
    { name = "time", version = "=0.1.44" },
]
