# Fill in the authentication values here or pass them as env vars with AOC_BOARD_ID,
# AOC_SESSION_COOKIE and DISCORD_BOT_TOKEN.
[aoc]
board_id = ""
session_cookie = ""
event = 2021

[discord]
bot_token = ""

[discord.schedule]
interval = 7200
channel_id = 1
