# Fill in the authentication values here or pass them as env vars with AOC_BOARD_ID,
# AOC_SESSION_COOKIE and DISCORD_BOT_TOKEN.
[aoc]
board_id = ""
session_cookie = ""
event_year = 2021

[discord]
bot_token = ""

[discord.schedule]
#          sec  min   hour   day of month   month   day of week   year
#          0    0     0      *             *       *             *
interval = "0 0 0 * * * *"
channel_id = 1
